# Generated by Django 5.0.3 on 2024-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_Date',
            field=models.DateField(null=True),
        ),
    ]
